variables:
  # MY_WORD: "something"
  # something is the default value for this variable
  # apk = alpine linux package manager 
  S3_BUCKET: "negar-gitlab-qa"

image: alpine:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

render_website:       # This job runs in the build stage, which runs first...
  stage: build
  script:
    - apk add markdown
    - mkdir -p public
    - markdown website.md | tee public/index.html
  artifacts:
      paths:
        - "public/index.html"

test_website:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - apk add libxml2-utils
    - xmllint --html public/index.html
    - "! grep bug public/index.html"
  dependencies:
    - "render_website"
  # rules:
  #   - if $CI_COMMIT_BRANCH =~ /^feature/


deploy_qa:      # This job runs in the deploy stage.
  environment: qa
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - apk add aws-cli
    - aws s3 cp ./public/ s3://$S3_BUCKET/ --recursive
  dependencies:
    - "render_website"
  rules:
    # - when: manual
    - if: $CI_COMMIT_BRANCH == "main"


deploy_staging:     
  variables: 
    S3_BUCKET: "negar-gitlab-staging"
  environment: staging
  stage: deploy 
  script:
    - apk add aws-cli
    - aws s3 cp ./public/ s3://$S3_BUCKET/ --recursive
  dependencies:
    - "render_website"
  rules:
    # - when: manual
    - if: $CI_COMMIT_TAG


deploy_prod:     
  variables: 
    S3_BUCKET: "negar-gitlab-prod"
  environment: prod
  stage: deploy 
  script:
    - apk add aws-cli
    - aws s3 cp ./public/ s3://$S3_BUCKET/ --recursive
  dependencies:
    - "render_website"
  rules:
    # - when: manual
      - if: $CI_COMMIT_TAG 
        when: manual